### PR TITLE
sorted events

### PR DESCRIPTION
**Pull request by Siunami**

### CODE REVIEW

**Review by rmw2 — COMMENTED** [review]
Is there actually a difference between the EventCard and EventCardOld components?  Seems like they should be one, and if we need any different behavior or styling we can just pass that through to the component to avoid duplicated code

**Comment by Siunami** [comment]
Difference is that you can't get to the attendee checkin via old event cards

**Comment by Siunami** [comment]
I can change to make it so component only renders attendee checkin section for current/future events.

**Comment by rmw2** [comment]
Ok maybe let’s add a Boolean prop to the regular event card (maybe isActive ?) and then conditionally allow the checkin flow based on that, and keep a single EventCard component

**Comment by Siunami** [comment]
Made the change. Good suggestion @rmw2

**Comment by rmw2** [comment]
Perf!

**Pull request merged**
